version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
  
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      tiemout: 500
      runas: ec2-user
  AfterInstall:
    - location: scripts/permissions.sh
      tiemout: 500
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      tiemout: 500
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      tiemout: 500
      runas: ec2-user
