version: 0.0
os: linux

files:
  - source: /
    destination : /home/ec2-user/server
  
  
permissions:
  object : /
  pattern : "**"
  owner: ec2-user
  group: ec2-user
  
hooks:
  BeforeInstall:
    - location: clean.sh
      tiemout: 500
      runas: ec2-user
  AfterInstall:
    - location: permissions.sh
      tiemout: 500
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      tiemout: 500
      runas: ec2-user
  ApplicationStop:
    - location: stop.sh
      tiemout: 500
      runas: ec2-user