version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Giving permissions
      - chmod 777 gradlew
  build:
    commands:
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build Complete!
artifacts:
  files:
    - build/libs/demo-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
